# Generated by Django 5.2.7 on 2025-10-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(default=0.0, help_text='Video duration in seconds'),
        ),
    ]
