# Generated by Django 5.2.6 on 2025-10-14 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='channel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
