# Generated by Django 5.2.7 on 2025-10-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_alter_channel_options_remove_channel_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='ch_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
