# Generated by Django 5.2.5 on 2025-10-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_alter_channel_options_remove_channel_banner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
